version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      APP_KEY: base64:tZc+c6xa3XqxzO1HGUyuKD0NFb9AFVPbjhlaI/2ifGE=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: db-fintech
      DB_USERNAME: root
      DB_PASSWORD: docker
      CACHE_STORE: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: db-fintech
      MYSQL_ROOT_PASSWORD: docker
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

